# Generated by Django 3.2.7 on 2021-09-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_uuid', models.UUIDField(verbose_name='Customer uuid')),
                ('phone', models.CharField(max_length=11, verbose_name='Customer phone')),
                ('chat_id', models.IntegerField(verbose_name='Telegram chat id')),
            ],
        ),
    ]
