# Generated by Django 3.2.7 on 2021-09-18 22:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_uuid',
            field=models.UUIDField(default=uuid.UUID('d88c700e-d480-4c76-96fa-f2feda047d54'), editable=False, primary_key=True, serialize=False),
        ),
    ]
