# Generated by Django 3.2.7 on 2021-09-18 22:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_uuid',
            field=models.UUIDField(default=uuid.UUID('cefb28cd-633c-4cf5-8f37-8a6e565ae973'), editable=False, primary_key=True, serialize=False),
        ),
    ]
