# Generated by Django 3.2.7 on 2021-09-18 14:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_uuid',
            field=models.UUIDField(default=uuid.UUID('84adb10a-b22d-4646-9cd4-2458f523fc40'), editable=False, primary_key=True, serialize=False),
        ),
    ]
